[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/status"
healthcheckTimeout = 30
restartPolicyType = "ALWAYS"
numReplicas = 1
sleepApplication = false
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 