[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1
sleepApplication = false
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 